name: Integration - Test Build & Code

on:
  push:
    branches:
      - main

env:
  CACHE_SERVICE: ${{vars.CACHE_SERVICE}}
  LOGGER_SERVICE: ${{vars.LOGGER_SERVICE}}
  JWT_SECRET_KEY: ${{vars.JWT_SECRET_KEY}}

jobs:
  test-code:
    runs-on: ubuntu-latest
    environment: CICD
    permissions:
      contents: read

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install PNPM
        run: npm install -g pnpm@latest-10

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: npm run test

  test-container-build:
    runs-on: ubuntu-latest
    environment: CICD
    permissions:
      contents: read

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Install PNPM
        run: npm install -g pnpm@latest-10

      - name: Install Dependencies
        run: pnpm install

      - name: Build Image
        run: docker build -t test-image:latest .

      - name: Remove Image
        run: docker image prune -a
